### ISSUE TITLE
output produces duplicated files with consecutive pluginOutputPostfix

### ISSUE THREAD

**Issue by bfiessinger** [zoobestik/csso-webpack-plugin#30]
when bundling my files through webpack csso-webpack-plugin produces more than one compiled file.
These files are then named like `style.min.css`, `style.min.min.css`, `style.min.min.min.css` and so on.

webpack.config:
```javascript
	{
		mode: 'production',
		entry: cssEntryPoints,
		output: {
			path: path.resolve(__dirname, 'dist/css'),
			filename: '[name].bundle.js'
		},
		optimization: {
			minimize: true,
			minimizer: [
				new TerserJSPlugin({
					terserOptions: {
						output: {
							comments: false,
						},
					},
					extractComments: false,
				}), 
				new CssMinimizerPlugin({})
			],
		},
		module: {
			rules: [
				{
					test: /\.(png|jpg|jpeg|gif|ico)$/,
					use: [
						{
							loader: 'file-loader',
							options: {
								name: '[name].[ext]',
								outputPath: '../images'
							}
						}
					],
				},
				{
					test: /\.svgz?$/,
					use: [
						{
							loader: 'file-loader',
							options: {
								name: '[name].[ext]',
								outputPath: '../images'
							}
						},
						{
							loader: 'svgo-loader'
						}
					],
				},
				{
					test: /\.(pc|sa|sc|c)ss$/,
					use: [
						{
							loader: MiniCssExtractPlugin.loader,
							options: {
								esModule: false
							}
						},
						'css-loader',
						'postcss-loader',
						'resolve-url-loader',
						'sass-loader',
					],
				},
			],
		},
		plugins: [
			new MiniCssExtractPlugin({
				filename: '[name].css',
				chunkFilename: '[id].css'
			}),
			new CssoWebpackPlugin({
				pluginOutputPostfix: 'min'
			})
		],
	},
```

**Comment by zoobestik** [comment]
Hi, @bfiessinger, problem was resolved? I have planned to see it on this week.

**Comment by bfiessinger** [comment]
@zoobestik with the config above the issue still exists.  
I've just made some small changes to bypass the problem.

```javascript
...
plugins: [
	new MiniCssExtractPlugin({
		filename: '[name].css',
		chunkFilename: '[id].css'
	}),
	new CssoWebpackPlugin({
		pluginOutputPostfix: 'min'
	})
],
...
```

is now

```javascript
...
plugins: [
	new MiniCssExtractPlugin({
		filename: '[name].min.css',
		chunkFilename: '[id].css'
	}),
	new CssoWebpackPlugin()
],
...
```
